---
- name: Onboard Linux Servers to Azure Arc-enabled servers with private endpoint connectivity
  hosts: <INSERT-HOSTS>
  tasks:
      - name: Download the Connected Machine Agent on Linux servers 
        become: yes
        get_url:
          url: https://aka.ms/azcmagent
          dest: ~/install_linux_azcmagent.sh
          mode: '700'
        when: ansible_system == 'Linux'
      - name: Install the Connected Machine Agent on Linux servers
        become: yes
        shell: bash ~/install_linux_azcmagent.sh
        when: ansible_system == 'Linux'
      - name: Connect the Connected Machine Agent on Linux servers to Azure Arc
        become: yes
        shell: sudo azcmagent connect --service-principal-id <INSERT-SERVICE-PRINCIPAL-CLIENT-ID> --service-principal-secret <INSERT-SERVICE-PRINCIPAL-SECRET> --private-link-scope <INSERT-PRIVATE-LINK-SCOPE> --resource-group <INSERT-RESOURCE-GROUP> --tenant-id <INSERT-TENANT-ID> --location <INSERT-REGION> --subscription-id <INSERT-SUBSCRIPTION-ID>
        when: ansible_system == 'Linux'
